# Generated by Django 4.1.1 on 2023-01-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EssayPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("subtitle", models.TextField()),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(default=models.TextField())),
            ],
        ),
    ]
