# Generated by Django 4.1.1 on 2023-01-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateTimeField()),
                ("content", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="essaypost",
            name="create_date",
            field=models.DateTimeField(),
        ),
    ]
