# Generated by Django 4.1.1 on 2023-01-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_devlog_alter_essaypost_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devlog",
            name="month",
            field=models.DateField(),
        ),
    ]
