# Generated by Django 4.1.1 on 2023-01-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_devlog_month"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_title", models.TextField()),
                ("author", models.TextField()),
                ("read_again", models.BooleanField()),
                ("notes", models.TextField()),
                ("highlights", models.URLField()),
                ("date_finished", models.DateTimeField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ]
                    ),
                ),
                ("goodreads_link", models.URLField()),
                (
                    "format_read",
                    models.TextField(
                        choices=[
                            ("Kindle", "Kindle"),
                            ("Audible", "Audible"),
                            ("Both", "Both"),
                        ]
                    ),
                ),
                ("times_read", models.IntegerField()),
            ],
        ),
    ]
